In [1]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn import model_selection, preprocessing
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import auc
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
import collections
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [46]:
data = pd.read_csv('task2_lemmas_train')
test = pd.read_csv('task2_lemmas_test')

In [47]:
olddata = data.copy()
data = data[['X','y']]

In [48]:
data['PoS'] = data['y'].map(lambda x: x[-1:])
data['y'] = data['y'].map(lambda x: x[:-2])
data.head()

              X            y PoS
0  vergognerete   vergognare   V
1  amnistiavate   amnistiare   V
2   menomazione  menomazione   N
3    sfaldavamo     sfaldare   V
4    sfodererei    sfoderare   V

In [49]:
exp_data = data.copy()
for x in exp_data.iterrows():
    i = 0
    while(x[1]['X'][i] == x[1]['y'][i]):
        i+=1
        if(i == len(x[1]['y']) or i == len(x[1]['X'])):
            x[1]['X'] = x[1]['y'] = ''
            break
    
    if(i < len(x[1]['y'])):
        x[1]['X'] = x[1]['X'][i:]
        x[1]['y'] = x[1]['y'][i:]

In [61]:
exp_data.head(n=200)

             X       y PoS
0        erete     are   V
1         vate      re   V
2                        N
3         vamo      re   V
4         erei     are   V
5          sti      re   V
6      hereste     are   V
7         eran     are   V
8         sser      re   V
9          ndo      re   V
10        sser      re   V
11        anno       e   V
12           i      re   V
13         ndo      re   V
14    erebbero     are   V
15   herebbero     are   V
16        sser      re   V
17         van      re   V
18          ta      re   V
19       ssero      re   V
20           n      re   V
21           n      re   V
22          te      re   V
23    erebbero     are   V
24         ssi      re   V
25         sti      re   V
26                       V
27      eremmo    iare   V
28                       V
29         ssi      re   V
..         ...     ...  ..
170     erebbe     are   V
171         va      re   V
172        nte      re   A
173        sse      re   V
174     ociamo  uocere   V
175        sse      re   V
176         ta      re   V
177       iene   enire   V
178         ta      re   V
179                      V
180       iamo     are   V
181         hi       o   N
182       rice     ore   A
183        mmo      re   V
184         ti      re   V
185         vo      re   V
186         vi      re   V
187         no      re   V
188          i       o   N
189      ssimo      re   V
190   erebbero     are   V
191       sser      re   V
192       erai     are   V
193                      N
194          à       e   V
195          ò     are   V
196         te    gere   V
197         to      re   V
198                      N
199                      V

[200 rows x 3 columns]

In [45]:
var = exp_data.copy()

In [63]:
exp_data.select(lambda x: exp_data['X'][x] == 'ti')

         X     y PoS
105     ti    re   V
136     ti    re   V
145     ti    re   V
184     ti    re   V
269     ti    re   V
270     ti    re   V
294     ti    re   V
574     ti    re   V
657     ti    re   V
841     ti    re   V
940     ti    re   V
953     ti    re   V
1080    ti    re   V
1102    ti  gere   V
1107    ti    re   V
1149    ti    re   V
1176    ti    re   V
1248    ti    re   V
1251    ti    re   V
1389    ti    re   V
1506    ti    re   V
1509    ti    re   V
1656    ti    re   V
1660    ti    re   V
2002    ti    re   V
2037    ti    re   V
2084    ti    re   V
2085    ti    re   V
2138    ti    re   V
2351    ti    re   V
...     ..   ...  ..
116473  ti    re   V
116514  ti    re   V
116549  ti    re   V
116550  ti    re   V
116573  ti    re   V
116682  ti    re   V
116716  ti    re   V
116736  ti    re   V
116779  ti    re   V
116816  ti    re   V
116824  ti    re   V
116929  ti    re   V
116951  ti    re   V
117074  ti    re   V
117195  ti    re   V
117326  ti    re   V
117425  ti    re   V
117433  ti    re   V
117434  ti    re   V
117544  ti    re   V
117550  ti    re   V
117598  ti    re   V
117642  ti    re   V
117879  ti    re   V
118158  ti    re   V
118215  ti    re   V
118263  ti    re   V
118417  ti    re   V
118471  ti    re   V
118491  ti    re   V

[1677 rows x 3 columns]

In [57]:
olddata.select(lambda x: x==115992)

            Id             X             y   y1   y2   y3   y4
115992  115993  suggellerete  suggellare+V  NaN  NaN  NaN  NaN